[build]
builder = "NIXPACKS"

[deploy]
startCommand = "streamlit run chatbot.py --server.address 0.0.0.0 --server.port $PORT --theme.base light --theme.primaryColor '#FF8C00'"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
PYTHONUNBUFFERED = "1"
STREAMLIT_SERVER_HEADLESS = "true"
STREAMLIT_BROWSER_GATHER_USAGE_STATS = "false"
